import type { CandidateCase } from '../types';

export const DEMO_WINDOW_ID = 'WIN-2026-09-07';

const createDefaultDocState = () => ({
  isAnalyzed: false,
  isAnalyzing: false,
  progress: { ocr: 0, extraction: 0, finbert: 0, reconciliation: 0 }
});

const createDefaultAudit = () => [
  { id: crypto.randomUUID(), timestamp: new Date().toISOString(), type: 'SYSTEM', description: 'Case created and entered screening pipeline.' },
  { id: crypto.randomUUID(), timestamp: new Date().toISOString(), type: 'SYSTEM', description: 'Screening complete. Placed into investigation queue.' }
];

export const DEMO_CANDIDATES: CandidateCase[] = [
  {
    transaction_id: 'TX-1042',
    fused_score: 0.941,
    cal_tx: 0.721,
    cal_doc: 0.891,
    cal_seq: 0.812,
    cal_graph: 0.224,
    conflict_tx_doc: 0.170,
    conflict_tx_seq: 0.091,
    tx_available: 1,
    doc_available: 1,
    seq_available: 1,
    graph_available: 1,
    investigated: false,
    status: 'QUEUED',
    events: createDefaultAudit(),
    document_analysis: createDefaultDocState(),
  },
  {
    transaction_id: 'TX-0817',
    fused_score: 0.912,
    cal_tx: 0.442,
    cal_doc: 0.0,
    cal_seq: 0.961,
    cal_graph: 0.923,
    conflict_tx_doc: 0.0,
    conflict_tx_seq: 0.519,
    tx_available: 1,
    doc_available: 0,
    seq_available: 1,
    graph_available: 1,
    investigated: false,
    status: 'QUEUED',
    events: createDefaultAudit(),
    document_analysis: createDefaultDocState(),
  },
  {
    transaction_id: 'TX-3319',
    fused_score: 0.887,
    cal_tx: 0.885,
    cal_doc: 0.865,
    cal_seq: 0.892,
    cal_graph: 0.811,
    conflict_tx_doc: 0.020,
    conflict_tx_seq: 0.007,
    tx_available: 1,
    doc_available: 1,
    seq_available: 1,
    graph_available: 1,
    investigated: false,
    status: 'QUEUED',
    events: createDefaultAudit(),
    document_analysis: createDefaultDocState(),
  },
  {
    transaction_id: 'TX-9921',
    fused_score: 0.651,
    cal_tx: 0.630,
    cal_doc: 0.550,
    cal_seq: 0.610,
    cal_graph: 0.680,
    conflict_tx_doc: 0.080,
    conflict_tx_seq: 0.020,
    tx_available: 1,
    doc_available: 1,
    seq_available: 1,
    graph_available: 1,
    investigated: false,
    status: 'QUEUED',
    events: createDefaultAudit(),
    document_analysis: createDefaultDocState(),
  },
  {
    transaction_id: 'TX-4402',
    fused_score: 0.410,
    cal_tx: 0.910,
    cal_doc: 0.100,
    cal_seq: 0.200,
    cal_graph: 0.150,
    conflict_tx_doc: 0.810,
    conflict_tx_seq: 0.710,
    tx_available: 1,
    doc_available: 1,
    seq_available: 1,
    graph_available: 1,
    investigated: false,
    status: 'QUEUED',
    events: createDefaultAudit(),
    document_analysis: createDefaultDocState(),
  },
];
